# Start with Hugo Docker image
FROM klakegg/hugo:0.93.2-ubuntu

# Download Curl, Node, NPM, and Firebase
RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install -y bash curl nodejs npm && \
    npm install -g firebase-tools

RUN useradd -s /bin/bash -m vscode && \
    groupadd docker &&\
    usermod -aG docker vscode

USER vscode

# Hugo dev server port
EXPOSE 1313